language: python
dist: trusty
sudo: required
python:
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3
  - sudo apt-get install -y aria2
  - sudo apt-get install -y sound-theme-freedesktop     
  - sudo apt-get install -y libnotify-bin
  - sudo apt-get install -y libqt5svg5
  - sudo apt-get install -y python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-pyqt5
  - sudo apt-get install -y pulseaudio
  - sudo apt-get install -y python3-psutil
  - sudo apt-get install -y youtube-dl  
  - sudo pip3 install requests
  - sudo pip3 install setproctitle

script:
 - sudo python3 setup.py install
 - persepolis --version
